sudo: required
services:
    - docker
    
before_install:
    - docker build -t hodgie/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true hodgie/docker-react npm run test
    
deploy:
    provider: elasticbeanstalk
    region: "eu-west-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-2-152555717435"
    bucket_path: "docker-react"
    on:
        branch: master
        
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY